#!/usr/bin/env bash
# Copyright 2024 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

case "$GOJSRUNTIME" in
	"node")
		exec node --stack-size=8192 ${GOJSRUNTIMEARGS:-} "$1" "${@:2}"
		;;
	"deno")
		exec deno run -A ${GOJSRUNTIMEARGS:-} "$1" "${@:2}"
		;;
	"bun")
		exec bun ${GOJSRUNTIMEARGS:-} "$1" "${@:2}"
		;;
	"browser")
		exec python3 -m webbrowser "file:///?$1"
		;;
	*)
		echo "Unknown Go JS runtime specified: $GOJSRUNTIME"
		exit 1
		;;
esac
