#!/usr/bin/env bash
# Copyright 2024 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

case "$GOJSRUNTIME" in
	"browser")
		SOURCE="${BASH_SOURCE[0]}"
		while [ -h "$SOURCE" ]; do
			DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
			SOURCE="$(readlink "$SOURCE")"
			[[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
		done
		DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

		exec go run "$DIR/go_js_wasm_exec_browser.go" "$1" "${@:2}"
		;;
	"deno")
		exec deno run -A ${GOJSRUNTIMEARGS:-} "$1" "${@:2}"
		;;
	"bun")
		exec bun ${GOJSRUNTIMEARGS:-} "$1" "${@:2}"
		;;
	"node" || "")
		exec node --stack-size=8192 ${GOJSRUNTIMEARGS:-} "$1" "${@:2}"
		;;
	*)
		echo "Unknown Go JS runtime specified: $GOJSRUNTIME"
		exit 1
		;;
esac
