name: all
on:
  push:
    branches: ["main"]
    paths-ignore:
      - .github/**
      - "!.github/workflows/all.yml"
      - api/**
      - doc/**
      - lib/**
      - misc/**
      - .gitattributes
      - .gitignore
      - codereview.cfg
      - CONTRIBUTING.md
      - go.env
      - LICENSE
      - PATENTS
      - README.md
      - SECURITY.md
  pull_request:
    paths-ignore:
      - .github/**
      - "!.github/workflows/all.yml"
      - api/**
      - doc/**
      - lib/**
      - misc/**
      - .gitattributes
      - .gitignore
      - codereview.cfg
      - CONTRIBUTING.md
      - go.env
      - LICENSE
      - PATENTS
      - README.md
      - SECURITY.md
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  all:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: false
      - run: ./all.bash
        working-directory: src
