name: all
on:
  push:
    branches: ["main"]
    paths-ignore:
      - .github/**
      - "!.github/workflows/all.yml"
      - api/**
      - doc/**
      - lib/**
      - misc/**
      - .gitattributes
      - .gitignore
      - codereview.cfg
      - CONTRIBUTING.md
      - go.env
      - LICENSE
      - PATENTS
      - README.md
      - SECURITY.md
  pull_request:
    paths-ignore:
      - .github/**
      - "!.github/workflows/all.yml"
      - api/**
      - doc/**
      - lib/**
      - misc/**
      - .gitattributes
      - .gitignore
      - codereview.cfg
      - CONTRIBUTING.md
      - go.env
      - LICENSE
      - PATENTS
      - README.md
      - SECURITY.md
jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ">=1"
      - run: ./all.bash
        working-directory: src
      - uses: actions/upload-artifact@v4
        with:
          path: |
            **
            !.git
