name: all
on:
  push:
    branches: ["main"]
    paths-ignore:
      - .github/**
      - "!.github/workflows/all.yml"
      - api/**
      - doc/**
      - lib/**
      - misc/**
      - .gitattributes
      - .gitignore
      - codereview.cfg
      - CONTRIBUTING.md
      - go.env
      - LICENSE
      - PATENTS
      - README.md
      - SECURITY.md
  pull_request:
    paths-ignore:
      - .github/**
      - "!.github/workflows/all.yml"
      - api/**
      - doc/**
      - lib/**
      - misc/**
      - .gitattributes
      - .gitignore
      - codereview.cfg
      - CONTRIBUTING.md
      - go.env
      - LICENSE
      - PATENTS
      - README.md
      - SECURITY.md
jobs:
  all:
    strategy:
      matrix:
        include:
          - { GOOS: linux, GOARCH: amd64 }
          - { GOOS: linux, GOARCH: arm64 }
          - { GOOS: windows, GOARCH: amd64 }
          - { GOOS: darwin, GOARCH: amd64 }
          - { GOOS: darwin, GOARCH: arm64 }
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: false
      - run: ./all.bash
        working-directory: src
        env:
          GOOS: ${{ matrix.GOOS }}
          GOARCH: ${{ matrix.GOARCH }}
      - id: get-version
        run: |
          version=$(cat VERSION.cache | grep -Po 'go[0-9]\.\S*' | cut -c 3-)
          echo "version=$version" >> "$GITHUB_OUTPUT"
      - uses: actions/upload-artifact@v4
        with:
          name: go${{ steps.get-version.outputs.version }}.${{ matrix.GOOS }}-${{ matrix.GOARCH }}
          path: |
            ./**
            !.git
